# Header
menu:
  Home: /
  Archives: /archives
  Tags: /tags
  Categories: /
  Github:
    url: https://github.com/JPValencia22/hexoMantenimiento
    icon: github

# Title on top left of menu. Leave empty to use main blog title
menu_title: Software Engineering III

# URL of the Home page image
index_cover: img/home-bg.png

# Default post title
default_post_title: Untitled

# Comments. Choose one by filling up the information
comments:
  # Disqus comments
  disqus_shortname:
  # Facebook comments
  facebook:
    appid:
    comment_count: 5
    comment_colorscheme: light

# Google Analytics Tracking ID
google_analytics:

# Addthis ID
addthis:

# set your own favicon
favicon:

#Name theme
theme: New-Theme

# Social Accounts
twitter_url:
twitter_handle:
facebook_url:
github_url: https://github.com/JPValencia22/hexoMantenimiento
gitlab_url:
linkedin_url:
mailto: